### PR TITLE
fix EditProfile

### LINKED ISSUE #13: Can't update birthday, in Edit Profile
If I see it correctly, in `saveBasic(...)` the birthday value is set to a string with format: `YYYY-MM-DD`.
And it appears that CloudKit prefers a valid timestamp.

JS console log:
```
[Error] t
_ckErrorCode: "BAD_REQUEST"
_extensionErrorCode: undefined
_reason: "Invalid value, expected type TIMESTAMP."
_recordName: "33407E99-***********"
_redirectURL: undefined
_retryAfter: undefined
_serverErrorCode: "BAD_REQUEST"
_subscriptionID: undefined
_uuid: undefined
_zoneID: undefined
message: "Invalid value, expected type TIMESTAMP."

t Prototype
	(anonymous function) (09f4d09.js:2:82482)
	(anonymous function) (54c6aed.js:1:131666)
	v (7854709.js:2:71646)
	(anonymous function) (7854709.js:2:71431)
	r (7854709.js:2:66121)
	h (7854709.js:2:66361)
	promiseReactionJob
```

### PR DESCRIPTION
**Pull request by thisIsTheFoxe**
Fixes #13

### CODE REVIEW

File: store/profile.ts [hunk 1]
```diff
@@ -159,15 +160,6 @@ export const actions: ActionTree<State, RootState> = {
...
 
-    if (updatedPrivate) {
-      let updatedScholar = Scholar.clone(scholar)
-      updatedScholar.scholarPrivate = {
-        recordName: updatedPrivate.recordName!,
-        action: CloudKit.ReferenceAction.DELETE_SELF
-      }
-      await updatedScholar.save()
-    }
-
```
Comment (moritzsternemann) [inline store/profile.ts:170]: I think we still need this in case the scholar didn't have a ScholarPrivate record before saving.

Maybe the check to save should be something like `updatedPrivate.recordName !== getters.scholar?.scholarPrivate.recordName` instead 🤔

**Review by moritzsternemann — CHANGES_REQUESTED** [review]
Thanks for the fix!

File: store/profile.ts (hunk 1 above)
Comment (thisIsTheFoxe) [reply store/profile.ts:170]: I think the problem with that is that [the email doesn't get saved](https://github.com/WWDCScholars/web-app/blob/5201131fec299fb2a8b0aecb05e952097e47fdf8/store/profile.ts#L127) if you **only** change the email. Just leaving it in often results in double saves which causes conflicts, which *works* but doesn't look nice..

```
_ckErrorCode: "CONFLICT"
_reason: "client oplock error updating record"
_recordName: "A6D87629-********"
_serverErrorCode: "CONFLICT"
message: "client oplock error updating record"
```
